# Generated by Django 3.0.5 on 2024-12-04 05:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0006_auto_20241204_1125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Report',
        ),
    ]
